"""
draft.ai — Setup Wizard
Guides the user through first-time configuration and writes the .env file.
Run this once before starting the app.
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

APP_DIR = Path(__file__).parent

# --- Always run inside the project venv to avoid system-Python version mismatches ---
_VENV_PYTHON = APP_DIR / "venv" / "Scripts" / "python.exe"
if _VENV_PYTHON.exists() and Path(sys.executable).resolve() != _VENV_PYTHON.resolve():
    result = subprocess.run([str(_VENV_PYTHON), __file__] + sys.argv[1:])
    sys.exit(result.returncode)


def clear():
    os.system("cls" if os.name == "nt" else "clear")


def header():
    clear()
    print("=" * 60)
    print("           draft.ai — Setup Wizard")
    print("=" * 60)
    print()


def ask(prompt, default=None, password=False, required=True):
    """Prompt the user for input with optional default."""
    if default:
        display = f"{prompt} [{default}]: "
    else:
        display = f"{prompt}: "

    while True:
        if password:
            import getpass
            value = getpass.getpass(display).strip()
        else:
            value = input(display).strip()

        if not value and default:
            return default
        if not value and required:
            print("  This field is required. Please enter a value.")
            continue
        return value


def ask_choice(prompt, choices, default=None):
    """Prompt user to pick from a numbered list."""
    print(f"\n{prompt}")
    for i, choice in enumerate(choices, 1):
        marker = " (default)" if choice == default else ""
        print(f"  {i}. {choice}{marker}")
    while True:
        raw = input(f"Enter number [1-{len(choices)}]: ").strip()
        if not raw and default:
            return default
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
        except ValueError:
            pass
        print("  Invalid choice, try again.")


def write_env(config: dict):
    """Write the .env file from collected config."""
    env_path = APP_DIR / ".env"
    lines = [
        "# draft.ai Configuration",
        "# Generated by setup wizard — do not commit this file",
        "",
        "# Mailbox",
        f"MAILBOX_EMAIL={config['email']}",
        f"IMAP_HOST={config['imap_host']}",
        f"IMAP_PORT={config['imap_port']}",
        f"IMAP_USERNAME={config['email']}",
        f"MAILBOX_PASSWORD={config['password']}",
        f"DRAFTS_FOLDER={config['drafts_folder']}",
        "",
        "# OpenAI",
        f"OPENAI_API_KEY={config['openai_key']}",
        f"OPENAI_MODEL={config['openai_model']}",
        "",
        "# Database",
        "DATABASE_URL=sqlite:///./email_drafts.db",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n  ✓ Configuration saved to {env_path}")


def check_dependencies():
    """Install pip dependencies if not already installed."""
    req_file = APP_DIR / "requirements.txt"
    if not req_file.exists():
        print("  ERROR: requirements.txt not found.")
        sys.exit(1)

    print("\n  Checking dependencies...")
    try:
        import fastapi
        import uvicorn
        import sqlalchemy
        import apscheduler
        import openai
        print("  ✓ Dependencies already installed.")
    except ImportError:
        print("  Installing dependencies (this may take a minute)...")
        subprocess.check_call([
            sys.executable, "-m", "pip", "install", "-r", str(req_file), "-q"
        ])
        print("  ✓ Dependencies installed.")


def test_imap(host, port, username, password):
    """Quick IMAP connection test."""
    import imaplib
    print(f"\n  Testing IMAP connection to {host}:{port}...")
    try:
        conn = imaplib.IMAP4_SSL(host, int(port))
        conn.login(username, password)
        conn.logout()
        print("  ✓ IMAP connection successful!")
        return True
    except Exception as e:
        print(f"  ✗ IMAP connection failed: {e}")
        return False


def test_openai(api_key, model):
    """Quick OpenAI API test."""
    print(f"\n  Testing OpenAI API key...")
    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        client.models.list()
        print("  ✓ OpenAI API key valid!")
        return True
    except Exception as e:
        print(f"  ✗ OpenAI API test failed: {e}")
        return False


def main():
    header()
    print("This wizard will configure draft.ai for first-time use.")
    print("You will need:")
    print("  - Your email address and password (or app password)")
    print("  - Your IMAP server hostname")
    print("  - Your OpenAI API key (from platform.openai.com)")
    print()
    input("Press Enter to begin...")

    # --- Step 1: Mailbox ---
    header()
    print("STEP 1 OF 3 — Email Account\n")
    print("Common IMAP hosts:")
    print("  Zoho Mail:    imappro.zoho.com  (or imap.zoho.com)")
    print("  Gmail:        imap.gmail.com")
    print("  Outlook/365:  outlook.office365.com")
    print("  Bluehost:     mail.yourdomain.com")
    print()

    email = ask("Email address")
    imap_host = ask("IMAP host", default="imappro.zoho.com")
    imap_port = ask("IMAP port", default="993")
    password = ask("Email password (or app password)", password=True)
    drafts_folder = ask_choice(
        "Drafts folder name (check your email client for exact name):",
        ["Drafts", "INBOX.Drafts", "Draft"],
        default="Drafts"
    )

    # Test IMAP
    imap_ok = test_imap(imap_host, imap_port, email, password)
    if not imap_ok:
        print()
        retry = ask("Connection failed. Continue anyway? (yes/no)", default="no")
        if retry.lower() != "yes":
            print("\nSetup cancelled. Please check your IMAP settings and try again.")
            input("Press Enter to exit...")
            sys.exit(1)

    # --- Step 2: OpenAI ---
    header()
    print("STEP 2 OF 3 — OpenAI API\n")
    print("Get your API key from: https://platform.openai.com/api-keys")
    print("Note: ChatGPT Plus subscription does NOT include API access.")
    print("You need a separate API account with billing enabled.")
    print()

    openai_key = ask("OpenAI API key", password=True)
    openai_model = ask_choice(
        "Which model to use:",
        ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo"],
        default="gpt-4o-mini"
    )

    # Install deps first so we can test OpenAI
    check_dependencies()
    openai_ok = test_openai(openai_key, openai_model)
    if not openai_ok:
        print()
        retry = ask("API test failed. Continue anyway? (yes/no)", default="no")
        if retry.lower() != "yes":
            print("\nSetup cancelled. Please check your OpenAI API key and try again.")
            input("Press Enter to exit...")
            sys.exit(1)

    # --- Step 3: Confirm & Save ---
    header()
    print("STEP 3 OF 3 — Confirm Settings\n")
    print(f"  Email:          {email}")
    print(f"  IMAP Host:      {imap_host}:{imap_port}")
    print(f"  Drafts Folder:  {drafts_folder}")
    print(f"  OpenAI Model:   {openai_model}")
    print(f"  API Key:        sk-...{openai_key[-6:] if len(openai_key) > 6 else '(set)'}")
    print()

    confirm = ask("Save these settings and complete setup? (yes/no)", default="yes")
    if confirm.lower() != "yes":
        print("\nSetup cancelled.")
        input("Press Enter to exit...")
        sys.exit(0)

    write_env({
        "email": email,
        "imap_host": imap_host,
        "imap_port": imap_port,
        "password": password,
        "drafts_folder": drafts_folder,
        "openai_key": openai_key,
        "openai_model": openai_model,
    })

    # Create start script
    start_bat = APP_DIR / "start.bat"
    start_bat.write_text(
        "@echo off\n"
        f"cd /d {APP_DIR}\n"
        "call venv\\Scripts\\activate\n"
        "start http://localhost:8000\n"
        "uvicorn app:app --host 0.0.0.0 --port 8000\n",
        encoding="utf-8"
    )
    print(f"  ✓ Start script saved to {start_bat}")

    # Done
    header()
    print("  ✓ Setup complete!\n")
    print("To start the app:")
    print(f"  Double-click:  {start_bat}")
    print("  Or run:        uvicorn app:app --host 0.0.0.0 --port 8000")
    print()
    print("The app will open at: http://localhost:8000")
    print()
    print("After launching, go to Settings to configure your:")
    print("  - Email signature")
    print("  - Reply tone")
    print("  - Custom AI instructions")
    print("  - Booking/website links")
    print()

    launch = ask("Launch the app now? (yes/no)", default="yes")
    if launch.lower() == "yes":
        subprocess.Popen(
            ["venv\\Scripts\\uvicorn.exe", "app:app", "--host", "0.0.0.0", "--port", "8000"],
            cwd=str(APP_DIR)
        )
        import webbrowser, time
        time.sleep(2)
        webbrowser.open("http://localhost:8000")
        print("\nApp launched! Check your browser.")

    input("\nPress Enter to exit setup...")


if __name__ == "__main__":
    main()
