"""
draft.ai — First-run setup wizard backend.
Serves the setup UI and handles connection testing + config saving.
"""

import imaplib
import os
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

_HERE = Path(__file__).parent

setup_app = FastAPI()
setup_app.mount("/static", StaticFiles(directory=str(_HERE / "static")), name="static")
_templates = Jinja2Templates(directory=str(_HERE / "templates"))


def _data_dir() -> Path:
    env_val = os.environ.get("DRAFT_AI_DATA_DIR")
    if env_val:
        return Path(env_val)
    return _HERE


@setup_app.get("/setup", response_class=HTMLResponse)
async def setup_page(request: Request):
    return _templates.TemplateResponse("setup.html", {"request": request})


@setup_app.post("/setup/test-imap")
async def test_imap(request: Request):
    data = await request.json()
    host = data.get("imap_host", "").strip()
    port = int(data.get("imap_port", 993))
    username = data.get("email", "").strip()
    password = data.get("password", "")
    if not host or not username or not password:
        return {"ok": False, "message": "Please fill in all fields first."}
    try:
        conn = imaplib.IMAP4_SSL(host, port)
        conn.login(username, password)
        conn.logout()
        return {"ok": True, "message": "Connection successful!"}
    except imaplib.IMAP4.error as e:
        return {"ok": False, "message": f"Login failed: {e}"}
    except Exception as e:
        return {"ok": False, "message": str(e)}


@setup_app.post("/setup/test-openai")
async def test_openai_key(request: Request):
    data = await request.json()
    api_key = data.get("api_key", "").strip()
    if not api_key:
        return {"ok": False, "message": "Please enter your API key first."}
    try:
        from openai import OpenAI, AuthenticationError
        client = OpenAI(api_key=api_key)
        client.models.list()
        return {"ok": True, "message": "API key verified!"}
    except Exception as e:
        msg = str(e)
        if "401" in msg or "invalid_api_key" in msg or "Incorrect API key" in msg:
            return {"ok": False, "message": "Invalid API key — check platform.openai.com/api-keys."}
        return {"ok": False, "message": msg}


@setup_app.post("/setup/save")
async def save_config(request: Request):
    data = await request.json()
    dd = _data_dir()
    dd.mkdir(parents=True, exist_ok=True)
    db_path = dd / "email_drafts.db"
    env_path = dd / ".env"

    lines = [
        "# draft.ai Configuration — generated by setup wizard",
        "",
        "# Mailbox",
        f"MAILBOX_EMAIL={data.get('email', '')}",
        f"IMAP_HOST={data.get('imap_host', '')}",
        f"IMAP_PORT={data.get('imap_port', '993')}",
        f"IMAP_USERNAME={data.get('email', '')}",
        f"MAILBOX_PASSWORD={data.get('password', '')}",
        f"DRAFTS_FOLDER={data.get('drafts_folder', 'Drafts')}",
        "",
        "# OpenAI",
        f"OPENAI_API_KEY={data.get('openai_key', '')}",
        f"OPENAI_MODEL={data.get('openai_model', 'gpt-4o-mini')}",
        "",
        "# Database",
        f"DATABASE_URL=sqlite:///{db_path}",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")
    return {"ok": True}
